"use client";
import {useState,useRef,useEffect,useLayoutEffect,ReactNode} from 'react';
import {ZoomIn,ZoomOut,ScanEye,Maximize,Hand} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {viewportGeometry,zoomFrame} from '@/lib/editor-geometry';

export default function PhotoViewport({width,height,children,pan=false,label,status,onDrop,onGestureStart}:{width:number;height:number;children:ReactNode;pan?:boolean;label:string;status?:ReactNode;onDrop?:(e:React.DragEvent<HTMLDivElement>)=>void;onGestureStart?:()=>void}){
  const [view,setView]=useState({width:600,height:500});const [zoom,setZoom]=useState(100);const [space,setSpace]=useState(false);const [grabbing,setGrabbing]=useState(false);const [over,setOver]=useState(false);
  const zoomTween=useRef<{frame:number;target:number}|null>(null);const scroll=useRef<HTMLDivElement>(null);const pending=useRef<{x:number;y:number}|null>(null);const gesture=useRef<{x:number;y:number;left:number;top:number}|null>(null);const pointers=useRef(new Map<number,{x:number;y:number}>());const pinch=useRef<{distance:number;zoom:number}|null>(null);
  const geometry=viewportGeometry(view,{width,height},zoom);const state=useRef({geometry,view,zoom});state.current={geometry,view,zoom};
  useEffect(()=>{const el=scroll.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setView({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(el);return()=>observer.disconnect()},[]);
  function stopZoom(){if(zoomTween.current){cancelAnimationFrame(zoomTween.current.frame);zoomTween.current=null}}
  useEffect(()=>()=>stopZoom(),[]);
  function changeZoom(value:number,anchor?:{x:number;y:number},immediate=false,focus?:{x:number;y:number}){
    const el=scroll.current;if(!el)return;stopZoom();
    const start=state.current;const target=Math.max(50,Math.min(400,Math.round(value)));const origin={x:el.scrollLeft,y:el.scrollTop};const fixed=anchor||{x:start.view.width/2,y:start.view.height/2};
    const apply=(progress:number)=>{const frame=zoomFrame(start.view,{width,height},start.zoom,target,progress,origin,fixed,focus);pending.current=frame.scroll;setZoom(frame.zoom);if(frame.zoom===state.current.zoom)applyScroll()};
    if(immediate||window.matchMedia('(prefers-reduced-motion: reduce)').matches){apply(1);return}
    const began=performance.now();const tick=(time:number)=>{const progress=Math.min(1,(time-began)/280);apply(progress);if(progress<1){zoomTween.current={frame:requestAnimationFrame(tick),target}}else zoomTween.current=null};
    zoomTween.current={frame:requestAnimationFrame(tick),target};
  }
  function focusEyes(){changeZoom(200,undefined,false,{x:.5,y:.4})}
  function applyScroll(){if(scroll.current&&pending.current){scroll.current.scrollLeft=pending.current.x;scroll.current.scrollTop=pending.current.y;pending.current=null}}
  useLayoutEffect(applyScroll,[zoom,view,width,height]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable=true],button,[role=slider]'))return;if(e.code==='Space'){e.preventDefault();setSpace(true)}};const up=(e:KeyboardEvent)=>{if(e.code==='Space')setSpace(false)};const blur=()=>{setSpace(false);gesture.current=null;pinch.current=null;pointers.current.clear();setGrabbing(false)};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
  useEffect(()=>{const el=scroll.current;if(!el)return;const wheel=(e:WheelEvent)=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const r=el.getBoundingClientRect();changeZoom((zoomTween.current?.target??state.current.zoom)*(e.deltaY>0?.9:1.1),{x:e.clientX-r.left,y:e.clientY-r.top})};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[width,height]);
  function down(e:React.PointerEvent<HTMLDivElement>){stopZoom();pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){const [a,b]=Array.from(pointers.current.values());pinch.current={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:state.current.zoom};gesture.current=null;onGestureStart?.();e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();e.stopPropagation();return}if(pan||space||e.button===1){e.preventDefault();e.stopPropagation();onGestureStart?.();const el=scroll.current!;gesture.current={x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId);setGrabbing(true)}}
  function move(e:React.PointerEvent<HTMLDivElement>){if(pointers.current.has(e.pointerId))pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch.current&&pointers.current.size>=2){e.preventDefault();e.stopPropagation();const [a,b]=Array.from(pointers.current.values()),r=scroll.current!.getBoundingClientRect();changeZoom(pinch.current.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.current.distance),{x:(a.x+b.x)/2-r.left,y:(a.y+b.y)/2-r.top},true);return}if(gesture.current){e.preventDefault();e.stopPropagation();const d=gesture.current;scroll.current!.scrollLeft=d.left-(e.clientX-d.x);scroll.current!.scrollTop=d.top-(e.clientY-d.y)}}
  function up(e:React.PointerEvent<HTMLDivElement>){pointers.current.delete(e.pointerId);if(pinch.current||gesture.current){e.stopPropagation();onGestureStart?.()}if(pointers.current.size<2)pinch.current=null;gesture.current=null;setGrabbing(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
  return <div className="photo-viewport"><div ref={scroll} role="region" aria-label={label} tabIndex={0} className={'photo-scroll '+(pan||space?'can-pan ':'')+(grabbing?'is-panning ':'')+(over?'drop-ready':'')} onPointerDownCapture={down} onPointerMoveCapture={move} onPointerUpCapture={up} onPointerCancelCapture={up} onDragOver={e=>{if(!onDrop||!e.dataTransfer.types.includes('application/x-lash'))return;e.preventDefault();e.dataTransfer.dropEffect='copy';setOver(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver(false)}} onDrop={e=>{setOver(false);onDrop?.(e)}}><div className="photo-track" style={{width:geometry.trackWidth,height:geometry.trackHeight}}><div className="photo-artboard" style={{width:geometry.width,height:geometry.height,left:geometry.left,top:geometry.top}}>{children}</div></div>{over&&<div className="drop-message">Solte para aplicar o mapping</div>}</div><div className="viewport-bottom"><span className="viewport-status">{status||<><Hand size={14}/>Arraste para observar</>}</span><div className="zoom-controls"><Button variant="ghost" size="icon" aria-label="Diminuir zoom" title="Diminuir zoom" disabled={zoom<=50} onClick={()=>changeZoom((zoomTween.current?.target??zoom)-25)}><ZoomOut size={16}/></Button><button className="zoom-value" onClick={()=>changeZoom(100)} title="Ajustar à tela">{Math.round(zoom)}%</button><Button variant="ghost" size="icon" aria-label="Aumentar zoom" title="Aumentar zoom" disabled={zoom>=400} onClick={()=>changeZoom((zoomTween.current?.target??zoom)+25)}><ZoomIn size={16}/></Button><span className="tool-divider"/><Button variant="ghost" className="zoom-preset" onClick={()=>changeZoom(100)} title="Ver foto inteira"><Maximize size={15}/><span>Ajustar</span></Button><Button variant="ghost" className="zoom-preset" onClick={focusEyes} title="Aproximar a região dos olhos"><ScanEye size={15}/><span>Olhos</span></Button></div></div></div>
}
