import {jsPDF} from 'jspdf';
import {CRITERIA,labelFor,Project} from './mapping-data';
export function makeDossier(p:Project,simulation:string,original:string){const doc=new jsPDF({unit:'mm',format:'a4'});const margin=18,width=174;const name=p.client||'Cliente';const date=new Date(p.date+'T12:00:00').toLocaleDateString('pt-BR');
function header(page:string){doc.setFillColor(20,20,20);doc.rect(0,0,210,25,'F');doc.setTextColor(255);doc.setFont('times','normal');doc.setFontSize(18);doc.text('MAPPING ATELIER',margin,15);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('NARRAIANA AUGUSTO',192,15,{align:'right'});doc.setTextColor(25);doc.setFontSize(8);doc.text(page.toUpperCase(),margin,36);doc.text(date,192,36,{align:'right'})}
function footer(){doc.setDrawColor(215);doc.line(margin,277,192,277);doc.setTextColor(100);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Um olhar pensado para você.',margin,284);doc.text(String(doc.getNumberOfPages()).padStart(2,'0'),192,284,{align:'right'})}
function imageFit(data:string,x:number,y:number,w:number,h:number){const ratio=p.photoWidth/p.photoHeight;let iw=w,ih=w/ratio;if(ih>h){ih=h;iw=h*ratio}doc.addImage(data,'JPEG',x+(w-iw)/2,y+(h-ih)/2,iw,ih,undefined,'FAST')}
header('Seu projeto de olhar');doc.setFont('times','normal');doc.setFontSize(30);const titleLines=doc.splitTextToSize(name,width).slice(0,2);doc.text(titleLines,margin,51);const titleHeight=titleLines.length*10;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(p.mapping||'Mapping personalizado',margin,55+titleHeight);const top=64+titleHeight;doc.setFillColor(247,247,247);doc.rect(margin,top,width,155,'F');imageFit(simulation,margin,top,width,155);doc.setFontSize(8);doc.setTextColor(95);doc.text('SIMULAÇÃO PERSONALIZADA',margin,top+161);doc.setFontSize(9);doc.text(doc.splitTextToSize('Uma proposta visual construída a partir da sua análise. A simulação é ilustrativa; o resultado da aplicação pode variar.',width),margin,top+172);footer();
doc.addPage();header('Ficha técnica & análise');let y=49;doc.setFont('times','normal');doc.setFontSize(24);doc.text('A assinatura do seu olhar',margin,y);y+=13;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(doc.splitTextToSize(`Cliente: ${name}`,width),margin,y);y+=12;
function section(title:string){if(y>236){footer();doc.addPage();header('Ficha técnica · continuação');y=49}doc.setFillColor(242,242,242);doc.rect(margin,y-5,width,10,'F');doc.setTextColor(25);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(title,margin+4,y+1);y+=14}
function row(label:string,value:string){const lines=doc.splitTextToSize(value||'Não informado',110);const h=Math.max(10,lines.length*5+4);if(y+h>269){footer();doc.addPage();header('Ficha técnica · continuação');y=49}doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(105);doc.text(label,margin,y);doc.setTextColor(25);doc.text(lines,margin+61,y);doc.setDrawColor(235);doc.line(margin,y+h-4,192,y+h-4);y+=h}
section('01  ANÁLISE DO OLHAR');for(const c of CRITERIA)row(c.title,labelFor(c.id,p.analysis[c.id]));y+=3;section('02  PLANO DE MAPPING');for(const [label,value] of [['Mapping',p.mapping],['Numeração (mm)',p.numbering],['Direcionamento',p.direction],['Técnica',p.technique],['Curvatura',p.curl],['Espessura (mm)',p.diameter],['Fios naturais (D / E)',(p.naturalRight||'Não informado')+' / '+(p.naturalLeft||'Não informado')],['Profissional',p.professional]])row(label,value);if(p.notes){y+=3;section('03  OBSERVAÇÕES');const lines:string[]=doc.splitTextToSize(p.notes,width);doc.setFont('helvetica','normal');doc.setFontSize(10);for(const line of lines){if(y>267){footer();doc.addPage();header('Observações · continuação');y=49}doc.text(line,margin,y);y+=5}}footer();
doc.addPage();header('Antes & proposta');doc.setFont('times','normal');doc.setFontSize(25);doc.text('O olhar, em perspectiva',margin,51);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(90);doc.text('FOTO ORIGINAL',margin,66);imageFit(original,margin,71,83,172);doc.text('SIMULAÇÃO',109,66);imageFit(simulation,109,71,83,172);doc.text(doc.splitTextToSize(`${name} · ${p.mapping||'Mapping personalizado'}`,width),margin,256);footer();doc.setProperties({title:`Mapping · ${name}`,subject:'Análise e simulação de mapping',author:p.professional||'Mapping Atelier'});return doc}
export function dossierFilename(client:string){return `Mapping-${client.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').slice(0,70)||'cliente'}.pdf`}
